### ISSUE TITLE
SRD readme image

### ISSUE THREAD

**Issue by agafon0ff** [agafon0ff/SimpleRemoteDesktop#1]
![SRD](https://user-images.githubusercontent.com/13070282/77161895-c8e37580-6abb-11ea-8cc4-c3d0ecc8676b.png)

**Comment by mlpa2112** [comment]
Hi Sergey, what is a good way to contact you to discuss your SRD? Thanks.

**Comment by agafon0ff** [comment]
Hello.  You can write here:
agafon0ff@mail.ru 

Вторник, 14 апреля 2020, 5:37 +03:00 от mlpa2112 <notifications@github.com>:

**Comment by agafon0ff** [comment]
agafon0ff@mail.ru
