### ISSUE TITLE
WebSokcet transmission

### ISSUE THREAD

**Issue by wangdemon** [agafon0ff/SimpleRemoteDesktop#6]
By reading JS code, I found that the mouse interaction function is transmitted through websocket client. After I bought the IP of public network, most of the current IP of public network only supports the HTTP prefix, but does not support the WS prefix of websocket protocol. How to deal with this situation?

**Comment by agafon0ff** [comment]
The WebSocket protocol is available only from JavaScript code, it is impossible to use it using other browser tools.
