### ISSUE TITLE
The code can be optimized

### ISSUE THREAD

**Issue by wangdemon** [agafon0ff/SimpleRemoteDesktop#8]
First of all, thank you very much for selflessly providing such high-quality code.
I found that there will be a great delay in the process of image transmission. By looking at the code, I found that because the image is of high quality, it is not compressed, and then it is cut into multiple small blocks for transmission.
![1](https://user-images.githubusercontent.com/20681339/147020598-764d3862-5e45-4625-a3fc-604d1d1b790f.png)
In fact, this can be done.In QT, there is an function for image compression. See the following code.
![2](https://user-images.githubusercontent.com/20681339/147020905-03e9109a-22e7-4e86-8952-d16f05192779.png)
A 1080p image can be compressed to 10 thousand ~ 30 thousand bytes, but if it is not compressed, there will be 1 million bytes.
By compressing the image, we can solve the problem of image transmission delay in the LAN. However, in the Internet, this scheme seems not to work. We can only solve the problem of transmission delay with the video streaming scheme.

**Comment by agafon0ff** [comment]
Yes. I compare the uncompressed images to find the change.
But the image is sent in a function where the image is converted to the PNG format (this is a compressed format). 
I also tried compressing in JPEG, but small images (tiles) are more efficiently compressed in PNG.
```cpp
void GraberClass::sendImage(int posX, int posY, int tileNum, const QImage &image)
{
    QByteArray bArray;
    QBuffer buffer(&bArray);
    buffer.open(QIODevice::WriteOnly);
    image.save(&buffer, "PNG");
    bArray.remove(0,PNG_HEADER_SIZE);

    emit imageTile(static_cast<quint16>(posX),static_cast<quint16>(posY),bArray,static_cast<quint16>(tileNum));
}
```
Yes, I have long come up with the implementation of image transmission using streaming video, but lately there is not a lot of time for hobby projects. Hopefully in the near future I will be able to implement this idea.

**Comment by wangdemon** [comment]
Don't segment the image, because segmenting the image is also very time-consuming. Directly compress the whole image, and then directly transmit the compressed image data.

**Comment by agafon0ff** [comment]
Image segmentation is needed to transfer fewer images.
For example, if I'm typing text, why transfer the entire desktop, if you can transfer only a small segment with a modified symbol.
Segments are sent to the browser only if they have changed.

**Comment by wangdemon** [comment]
Yes, what you said is very reasonable. But you ignore a problem. Image segmentation is very time-consuming, and it will take some time when using comparison operation of QByteArray class. You can see the effect picture below.
![动画1](https://user-images.githubusercontent.com/20681339/147641890-76bca5dc-5e74-490f-8bc4-1cc8b1f3e70e.gif)

**Comment by agafon0ff** [comment]
Yes. Looks faster.
I will try to do some tests with your proposal.
Thank you for your persistence.
